module.exports = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  VALIDATION: {
    REQUIRED: 'REQUIRED',
    LENGTH: 'LENGTH',
    INVALID_EMAIL: 'INVALID_EMAIL',
    UNIQUE: 'UNIQUE'
  }
};
